version: '3'
services:
  load-balancer:
    image: nginx:1.14-alpine
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/conf.d/api.conf
    ports:
      - "8080:8080"
    restart: always
    env_file:
      - ./load-balancer/.env
    links:
      - api
  api:
    build: ./api
    ports:
      - "3000:3000"
    restart: always
    env_file:
      - ./api/.env